import type { Metadata } from "next"
import "./globals.css";
import { Roboto } from 'next/font/google'
import {NextUIProvider} from "@nextui-org/react";

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <NextUIProvider>
        {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
