import type { Metadata } from "next"
import "./globals.css";
import { Montserrat } from "next/font/google";
import { Playfair_Display } from "next/font/google";
import { Roboto } from 'next/font/google'
import { Quicksand } from "next/font/google";

import {NextUIProvider} from "@nextui-org/react";

const qs = Quicksand({
  subsets: ['latin'],
  weight: '500'
})

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: '200'
})

const pf = Playfair_Display({
  subsets: ['latin'],
  weight: '400'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={qs.className}>
      <body>
        <NextUIProvider>
        {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
